### ISSUE TITLE
Learn how ray extensions workflow are built ( `.github` and [`github-actions`](https://github.com/raycast/github-actions))

### ISSUE THREAD

**Issue by Yukaii** [BlastLauncher/blast#10]

**Comment by Yukaii** [comment]
- https://github.com/raycast/extensions/actions/runs/3955837699/jobs/6774472026#step:5:249
- https://github.com/raycast/github-actions/blob/2f74efbb1dde6c769599e067b0c18599525ec40c/ray-cli/ray_cli.sh#L65


All build operation are hidden behind ray cli, so we just build our own stuff.

**Comment by Yukaii** [comment]
https://github.com/raycast/github-actions/blob/2f74efbb1dde6c769599e067b0c18599525ec40c/get-command/get_command.sh#L8-L12

Extensions get published for every new push

```sh
if [ "$event_name" == 'push' ]; then
    command="publish"
elif [ "$event_name" == 'pull_request' ]; then
    command="build"
else
```

**Comment by Yukaii** [comment]
https://github.com/raycast/github-actions/blob/2f74efbb1dde6c769599e067b0c18599525ec40c/ray/action.yml#L62-L68

Take every outputs from previous actions and run ray cli to build/publish extension:

```yml
      uses: raycast/github-actions/ray-cli@v1.13.0
      with:
        paths: ${{ steps.get_changed_extensions.outputs.paths }}
        command: ${{ steps.get_command.outputs.command }}
        npm_token: ${{ inputs.npm_token }}
        extension_schema: ${{ inputs.extension_schema }}
        allow_owners_only_for_extensions: ${{ inputs.allow_owners_only_for_extensions }}
```

So we can take everything in [ray/action.yml](https://github.com/raycast/github-actions/blob/master/ray/action.yml#L62-L68) except these lines and add our own workflow to publish extensions.
